---
sudo: false
language: ruby
script: "bundle exec rake"
matrix:
  include:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.3.3
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"